### ISSUE TITLE
哥们，npm i 安装不了所有模块

### ISSUE THREAD

**Issue by wuxinwei240** [redgang/redx-vue#1]
npm i 安装不了所有模块，只能一个一个的安装，搞不清楚这个什么原因，有的电脑是会出现，有的电脑不会出现

**Comment by wuxinwei240** [comment]
![Uploading 5EB132A1-A42B-4AB0-A617-10C6046C109B.png…]()
![Uploading bc.png…]()
![Uploading bc.png…]()

npm start 运行报错

**Comment by redgang** [comment]
看不了你发的图片，安装慢可能是npm服务器连接或网络问题
安装一下淘宝镜像 npm install -g cnpm --registry=https://registry.npm.taobao.org
用 cnpm i 进行安装试试
