### ISSUE TITLE
c-header 组件如何在首页不显示？

### ISSUE THREAD

**Issue by yisibl** [redgang/redx-vue#4]
![image](https://cloud.githubusercontent.com/assets/2784308/19978425/da6ac246-a231-11e6-900f-80e3e2196850.png)

上面这个组件如何在首页不显示？

另外 v-footer 组件是如何控制在哪个 views 是否显示的？

非常感谢！

**Comment by redgang** [comment]
在app.vue中控制<v-header :routes="routes"></v-header>是否展现就可以了，footer组件同理，目前主要是通过路由路径判断的，也可以通过事件机制或双向绑定数据来控制

**Comment by yisibl** [comment]
好的，我看到了，谢谢哈！
