### ISSUE TITLE
footer 组件 link-active 的 class 切换问题

### ISSUE THREAD

**Issue by yisibl** [redgang/redx-vue#5]
![image](https://cloud.githubusercontent.com/assets/2784308/19999489/9f7867c0-a2ad-11e6-898a-3fa632ad12e3.png)

footer 切换的时候第一个始终存在 `link-active` 的 class，如何去掉？

**Comment by redgang** [comment]
样式可以通过:class方式，根据路由或数据变量动态控制，比如<a :class="{'active': $route.path === '/'}" href="#!/">...</a>
